deploy, pre-commit scripts tweaked

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,21 +1,21 @@
-    #!/bin/sh
-    # to enable:
-    # git config core.hooksPath .githooks
-    # Define the maximum allowed file size in bytes (e.g., 10MB)
-    # MAX_FILE_SIZE_BYTES=10485760
-    MAX_FILE_SIZE_BYTES=1048
+#!/bin/sh
+# to enable this hook run:
+# git config core.hooksPath .githooks
+# also, run this: git config --global core.excludesfile ~/.gitignore_global
+# Define the maximum allowed file size in bytes (e.g., 10MB)
+MAX_FILE_SIZE_BYTES=10485760
 
-    # Get a list of added files in the current commit
-    ADDED_FILES=$(git diff --cached --name-only --diff-filter=A)
+# Get a list of added files in the current commit
+ADDED_FILES=$(git diff --cached --name-only --diff-filter=A)
 
-    for FILE in $ADDED_FILES; do
-        if [ -f "$FILE" ]; then
-            FILE_SIZE=$(wc -c < "$FILE")
-            if [ "$FILE_SIZE" -gt "$MAX_FILE_SIZE_BYTES" ]; then
-                echo "Error: File '$FILE' is too large ($FILE_SIZE bytes). Maximum allowed size is $MAX_FILE_SIZE_BYTES bytes."
-                exit 1 # Exit with a non-zero status to prevent the commit
-            fi
+for FILE in $ADDED_FILES; do
+    if [ -f "$FILE" ]; then
+        FILE_SIZE=$(wc -c < "$FILE")
+        if [ "$FILE_SIZE" -gt "$MAX_FILE_SIZE_BYTES" ]; then
+            echo "Error: File '$FILE' is too large ($FILE_SIZE bytes). Maximum allowed size is $MAX_FILE_SIZE_BYTES bytes."
+            exit 1 # Exit with a non-zero status to prevent the commit
         fi
-    done
+    fi
+done
 
-    exit 0 # Allow the commit to proceed
+exit 0 # Allow the commit to proceed
